# -*- coding: utf-8 -*-
"""Data Analysis of the Power Generation by Fuel Source 11-30-2023 | acaffeinatedcoder.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TmN-qOQ5J7VNVFAP0qyT13uwZOBzcwRI

Resources:
  Power Generation by Fuel Source (in GWh), 1990-2020
  Published on November 30th, 2023

---
link: https://data.gov.ph/index/public/dataset/Power%20Generation%20by%20Fuel%20Source,%201990-2020/mhb14dc0-8tio-af0u-6nac-euxrn6bz48rm

**Trend Analysis**
1. How was the total power generation changed from 1990 to 2020?
2. What are the trends in power generation for each fuel source over the years?
3. Which fuel sources have seen the most significant growth or decline over time?

**Comparison and Proportions**
4. What is the contribution of each fuel source to the Grand Total in different decades (e.g., 1990s, 2000s, 2010s)?
5. Which fuel source had the highest average power generation, and which had the lowest?
6. How has the share of renewable energy sources (Biomass, Geothermal, Hydro, Solar, Wind) evolved over the years?

**Peak and Trough Analysis**
7. In which years did each fuel source achieve its maximum and minimum power generation?
8. What are the years with the highest and lowest Grand Total, and what fuel sources dominated those years?

**Comparisons Across Sources**
9. How does renewable energy generation compare to non-renewable energy generation over time?
10. How do seasonal or cyclical patterns (if any) manifest across different fuel sources?

**Correlation and Relationships**
11. Are there any noticeable correlations between the growth of certain renewable sources (e.g., Solar and Wind)?
12. How does the reduction in Coal usage align with changes in other energy sources?

**Forecasting and Predictions**
13. Based on historical data, can you predict the power generation for each fuel source in the next decade?
14. What are the potential scenarios for the Grand Total if current trends continue?

**Policy and Impact Analysis**
15. How has the adoption of renewable energy sources affected the dependency on non-renewable sources?
16. What might be the implications of current trends on future energy policies?
"""

!pip install pandas
import pandas as pd
import matplotlib.pyplot as plt

# NOTE: Due to some difficulties, the CSV File retrieved from the source link
#       was converted into a XLSX File.
#       The 'pgfs' stands for 'Power Generated by Fuel Source'.

pgfs = pd.read_excel('/content/pgfs.xlsx')
pgfsDF = pd.DataFrame(pgfs)
pgfsDF

# Cleaning Stage
pgfsDF['Cleaned Grand Total'] = (pgfsDF['Biomass'] + pgfsDF['Coal'] + pgfsDF['Geothermal'] + pgfsDF['Hydro'] + pgfsDF['Natural Gas'] + pgfsDF['Oil-based'] + pgfsDF['Solar'] + pgfsDF['Wind'])

# NOTE: Grand Total Column and user-generated Cleaned Grand Total Column are not of the same value.
#       Upon manual calculations, Cleaned Grand Total Column proved to be more accurate.
#       Grand Total Column will be dropped for its innacuracy.
pgfsDF

pgfsDF = pgfsDF.drop(columns=['Grand Total'], axis=1)
pgfsDF = pgfsDF.rename(columns={'Cleaned Grand Total': 'Grand Total'})
pgfsDF

# 1. Total Power Generation change from 1990 - 2020

plt.figure(figsize=(10, 6))
plt.plot(pgfsDF['Years'], pgfsDF['Grand Total'], marker='.', markersize=10)
plt.title('Total Power Generation change from 1990 - 2020')
plt.xlabel('Years')
plt.ylabel('Grand Total')
plt.grid()
plt.show()

# 2. Trends in Power Generation for each Fuel Source

list_of_years = list(pgfsDF['Years'])
list_of_fuels = ['Biomass', 'Coal', 'Geothermal', 'Hydro', 'Natural Gas', 'Oil-based', 'Solar', 'Wind']
length = len(list_of_fuels)

rows = (length + 1) // 2
cols = 2 if length > 1 else 1

highest_GWh = []
for i in list_of_fuels:
  highest_GWh.append(pgfsDF[i].max())

highest_GWh.sort()
length_h = len(highest_GWh)
high_GWh = highest_GWh[length_h - 1]
highest_GWh.clear()
six_div = high_GWh / 6

if (high_GWh % 6 == 0):
  for i in range(6):
    highest_GWh.append(high_GWh)
    high_GWh -= six_div
else:
  for i in range(6):
    highest_GWh.append(high_GWh)
    high_GWh -= six_div


plt.figure(figsize=(20, 16))
plt.suptitle('Trends in Power Generation for each Fuel Source over the Years')
for i in range(length):
    plt.subplot(rows, cols, i + 1)
    plt.plot(pgfsDF['Years'], pgfsDF[list_of_fuels[i]], marker='.', markersize=10)
    plt.title(list_of_fuels[i])
    plt.xlabel('Years')
    plt.ylabel('Grand Total')
    plt.xticks(list_of_years, rotation=45)
    plt.yticks(highest_GWh)
    plt.grid()

plt.tight_layout()
plt.show()

# 3. Fuel Source Growth and Decline over time

list_of_years = list(pgfsDF['Years'])
list_of_fuels = ['Biomass', 'Coal', 'Geothermal', 'Hydro', 'Natural Gas', 'Oil-based', 'Solar', 'Wind']
length = len(list_of_fuels)

rows = (length + 1) // 2
cols = 2 if length > 1 else 1

plt.figure(figsize=(20, 16))
plt.suptitle('Trends in Power Generation for each Fuel Source')
for i in range(length):
    plt.subplot(rows, cols, i + 1)
    plt.plot(pgfsDF['Years'], pgfsDF[list_of_fuels[i]], marker='.', markersize=10)
    plt.title(list_of_fuels[i])
    plt.xlabel('Years')
    plt.ylabel('Grand Total')
    plt.xticks(list_of_years, rotation=45)
    plt.grid()

plt.tight_layout()
plt.show()

# 4. Contribution of each Fuel Source to the Grand Total per Decade

nineties = pgfsDF[(pgfsDF['Years'] >= 1990) & ( pgfsDF['Years'] <= 1999)]
twothou = pgfsDF[(pgfsDF['Years'] >= 2000) & ( pgfsDF['Years'] <= 2009)]
twotens = pgfsDF[(pgfsDF['Years'] >= 2010) & ( pgfsDF['Years'] <= 2019)]
twotwen = pgfsDF[(pgfsDF['Years'] >= 2020) & ( pgfsDF['Years'] <= 2029)]

nines = []
twoth = []
twote = []
twotw = []

for i in list_of_fuels:
  nines.append(nineties[i].sum())
  twoth.append(twothou[i].sum())
  twote.append(twotens[i].sum())
  twotw.append(twotwen[i].sum())

plt.figure(figsize=(20, 16))
plt.suptitle('Contribution of each Fuel Source to the Grand Total per Decade')
plt.subplot( rows, cols, 1)
plt.bar(list_of_fuels, nines, label='1990s')
plt.xlabel('Fuel Sources')
plt.ylabel('Grand Total')
plt.title('1990s')
plt.grid()

plt.subplot( rows, cols, 2)
plt.bar(list_of_fuels, twoth, label='2000s')
plt.xlabel('Fuel Sources')
plt.ylabel('Grand Total')
plt.title('2000s')
plt.grid()

plt.subplot( rows, cols, 3)
plt.bar(list_of_fuels, twote, label='2010s')
plt.xlabel('Fuel Sources')
plt.ylabel('Grand Total')
plt.title('2010s')
plt.grid()

plt.subplot( rows, cols, 4)
plt.bar(list_of_fuels, twotw, label='2020s')
plt.xlabel('Fuel Sources')
plt.ylabel('Grand Total')
plt.title('2020s')
plt.grid()

plt.tight_layout()
plt.show()

# 5. Highest adn Lowest Average Power Generation per Fuel Source

power_gen_ave = []
for i in list_of_fuels:
  power_gen_ave.append(pgfsDF[i].mean())

power_gen_labels = []
for i in list_of_fuels:
  power_gen_labels.append(i + '\n(' + str(round(pgfsDF[i].mean(), 2)) + ' GWh)')

plt.figure(figsize=(10, 6))
plt.bar(power_gen_labels, power_gen_ave)
plt.title('Average Power Generation per Fuel Source 1990 to 2020')
plt.xlabel('Fuel Sources')
plt.ylabel('Average Power Generation')
plt.xticks(rotation = 20, ha = 'center')
plt.grid()
plt.tight_layout()
plt.show()

# 6. Share of Renewable Energy Resources

renewables = ['Biomass', 'Geothermal', 'Hydro', 'Solar', 'Wind']
ren_color = ["#8B4513", "#228B22", "#1E90FF", "#FFD700", "#A9D9FF"]
rc = 0

plt.figure(figsize=(20, 16))
for i in range(length):
    if list_of_fuels[i] in renewables:
      plt.plot(pgfsDF['Years'], pgfsDF[list_of_fuels[i]], label=list_of_fuels[i], c=ren_color[rc], linewidth = 2, marker='P', markersize=15, linestyle=':')
      rc += 1
    else:
      plt.plot(pgfsDF['Years'], pgfsDF[list_of_fuels[i]], marker='.', markersize=10, alpha=0.3)
    plt.legend( fontsize = 25, title = 'Renewable Fuel Sources')

plt.title('Share of Renewable Energy Sources')
plt.xlabel('Years')
plt.ylabel('Grand Total')
plt.xticks(list_of_years, rotation=45)
plt.grid()
plt.tight_layout()
plt.show()

# 7. Year of Minimum and Maximum Peak of Power Generation per Fuel Source

id_of_max = []
id_of_min = []

for i in list_of_fuels:
  id_of_max.append(pgfsDF[i].idxmax())
  id_of_min.append(pgfsDF[i].idxmin())

max_year = []
min_year = []

for i in id_of_max:
  max_year.append(pgfsDF['Years'][i])

for i in id_of_min:
  min_year.append(pgfsDF['Years'][i])


print('Years of Maximum Peak of Power Generation per Fuel Source')
for i in list_of_fuels:
  print(i + ': ' + str(max_year[list_of_fuels.index(i)]))
print()
print('Years of Minimum Peak of Power Generation per Fuel Source')
for i in list_of_fuels:
  print(i + ': ' + str(min_year[list_of_fuels.index(i)]))

# 8. Years with the Highest and Lowest Grand Total along with the Fuel Source that has the highest contribution

id_of_max = pgfsDF['Grand Total'].idxmax()
id_of_min = pgfsDF['Grand Total'].idxmin()

maxim = []
minim = []

for i in list_of_fuels:
  maxim.append(pgfsDF[i][id_of_max])
  minim.append(pgfsDF[i][id_of_min])

max_i = max(maxim)
min_i = max(minim)

print('Year with the Highest Grand Total: ' + str(pgfsDF['Years'][id_of_max]))
print('Highest Contributing Fuel Source: ' + list_of_fuels[maxim.index(max_i)] + '\n')
print('Year with the Lowest Grand Total: ' + str(pgfsDF['Years'][id_of_min]))
print('Lowest Contributing Fuel Source: ' + list_of_fuels[minim.index(min_i)])
print()

# 9. Comparison of Renewable Energy Generation and Non-renewable Energy Generation over Time

renew_total = []
nonrenew_total = []

for x in pgfsDF.index:
  sum_r = 0
  sum_n = 0
  for i in list_of_fuels:
    if i in renewables:
      sum_r += pgfsDF[i][x]
    else:
      sum_n += pgfsDF[i][x]
  renew_total.append(sum_r)
  nonrenew_total.append(sum_n)

print(renew_total)
print(nonrenew_total)

fig = plt.figure(figsize=(20, 16))
fig.set_facecolor('#a0a0a0')

plt.plot(pgfsDF['Years'], renew_total, label='Renewable Energy', c='#FF0000', linewidth = 2,)
plt.plot(pgfsDF['Years'], nonrenew_total, label='Non-Renewable Energy', c='#00FF00', linewidth = 2,)
plt.title('Comparison of Renewable Energy Generation and Non-renewable Energy Generation over Time', fontsize=26)
plt.xlabel('Years', fontsize=16)
plt.ylabel('Grand Total', fontsize=16)
plt.xticks(list_of_years, rotation=45)
plt.legend(fontsize = 25, title = 'Fuel Sources')
plt.grid()
plt.tight_layout()
plt.show()

# 10. How do Seasonal or Cyclical Patterns manifest across different Fuel Sources

# NOTE: Could not answer due to lack of monthly and seasonal data.
#       Cannot analyze nor present as fuel source generation (in GWh) are compiled to yearly outputs only.

# 11. Noticeable correlations between the Growth of certain Renewable Fuel Sources

renewables = ['Biomass', 'Geothermal', 'Hydro', 'Solar', 'Wind']
ren_color = ["#8B4513", "#228B22", "#1E90FF", "#FFD700", "#A9D9FF"]
rc = 0

plt.figure(figsize=(20, 16))
for i in range(length):
    if list_of_fuels[i] in renewables:
      plt.plot(pgfsDF['Years'], pgfsDF[list_of_fuels[i]], label=list_of_fuels[i], c=ren_color[rc], linewidth = 2, marker='P', markersize=15, linestyle=':')
      rc += 1

plt.legend(fontsize = 25, title = 'Growth of Renewable Fuel Sources')
plt.title('Share of Renewable Energy Sources', fontsize=16)
plt.xlabel('Years')
plt.ylabel('Grand Total')
plt.xticks(list_of_years, rotation=45)
plt.grid()
plt.tight_layout()
plt.show()

# 12. Alignment of reduction of Coal usage with other energy sources

renewables = ['Biomass', 'Geothermal', 'Hydro', 'Solar', 'Wind']
rc = 0

plt.figure(figsize=(20, 16))
for i in range(length):
    if list_of_fuels[i] in renewables:
      plt.plot(pgfsDF['Years'], pgfsDF[list_of_fuels[i]], label=list_of_fuels[i])
    elif list_of_fuels[i] == 'Coal':
      plt.plot(pgfsDF['Years'], pgfsDF[list_of_fuels[i]], label=list_of_fuels[i], linewidth = 4, marker='P', markersize=15, linestyle=':', c='#000000')
    else:
      plt.plot(pgfsDF['Years'], pgfsDF[list_of_fuels[i]], label=list_of_fuels[i])

plt.legend(fontsize = 25, title = 'Fuel Sources')
plt.title('Share of Renewable Energy Sources')
plt.xlabel('Years')
plt.ylabel('Grand Total')
plt.xticks(list_of_years, rotation=45)
plt.grid()
plt.tight_layout()
plt.show()

# 13. Prediction of Power Generation for each Fuel Source in the Next Decade according to Historical Data
# 13.1. Pattern Recognition of Ration Increase

# NOTE: Generation of other Fuel Sources over the years are fluctuating.
#       This method may not yield the correct estimate.

solar_gen = list(pgfsDF['Solar'])

# Get the percentage of increase
solar_per = []
for i in range(len(solar_gen) - 1):
  if solar_gen[i] == 0:
    solar_per.append(0)
  else:
    solar_per.append(round((((solar_gen[(i + 1)] - solar_gen[i]) / solar_gen[i]) * 100), 2))
# Ditched due to incorrect prediction
'''
average_solar_per = sum(solar_per) / len(solar_per)
print('Average Ratio Increase of Solar Generation: ' + str(round(average_solar_per, 2)) + '%')
for i in range(10):
  solar_gen.append(round(solar_gen[len(solar_gen) - 1] * (1 + average_solar_per / 100)))
  solar_per.append(round((((solar_gen[(len(solar_gen) - 1)] - solar_gen[len(solar_gen) - 2]) / solar_gen[len(solar_gen) - 2]) * 100), 2))
'''

average_solar_per = (solar_per[-1] + solar_per[-2] + solar_per[-3] + solar_per[-4]) / 4
print('Average Ratio Increase of Solar Generation in the Last 4 Years: ' + str(round(average_solar_per, 2)) + '%')
for i in range(10):
  solar_gen.append(round(solar_gen[len(solar_gen) - 1] * (1 + average_solar_per / 100)))
  solar_per.append(average_solar_per)
  average_solar_per = (solar_per[-1] + solar_per[-2] + solar_per[-3] + solar_per[-4]) / 4

print('Percentage of Change per Year')
for i in range(len(solar_per)):
  print(str(solar_gen[i]) + ' -> ' + str( solar_gen[i + 1]) + ' = ' + str(round(solar_per[i], 2)) + ' percent.')

# 13.2. Average Ratio Increase
coal_gen = list(pgfsDF['Coal'])

# Get the percentage of increase
coal_per = []
for i in range(len(coal_gen) - 1):
  coal_per.append(((coal_gen[(i + 1)] - coal_gen[i]) / coal_gen[i]) * 100)

average_ratio_coal = sum(coal_per) / len(coal_per)
print('Average Ratio Increase of Coal Generation: ' + str(round(average_ratio_coal, 2)) + '%')

for i in range(10):
  buffer = round(coal_gen[len(coal_gen) - 1] * (1 + average_ratio_coal / 100))
  coal_gen.append(round(coal_gen[len(coal_gen) - 1] * (1 + average_ratio_coal / 100)))
  for i in range(len(coal_gen) - 1):
    coal_per.append(round((((coal_gen[(i + 1)] - coal_gen[i]) / coal_gen[i]) * 100), 5))
  print('Power generated is ' + str(buffer) + ' due to ' + str(coal_per[-1]) + '% increase.')
  average_ratio_coal = sum(coal_per) / len(coal_per)

print(coal_gen)
#print('Percentage of Change per Year')
#for i in range(len(coal_per)):
#  print(str(coal_gen[i]) + ' -> ' + str( coal_gen[i + 1]) + ' = ' + str(round(coal_per[i], 2)) + ' percent.')

# 14. Potential Scenarios for the Grand Total accounting for Current Trends

total_gen = list(pgfsDF['Grand Total'])

# Get the percentage of increase
total_per = []
for i in range(len(total_gen) - 1):
  total_per.append(((total_gen[(i + 1)] - total_gen[i]) / total_gen[i]) * 100)

average_ratio_total = sum(total_per) / len(total_per)
print('Average Ratio Increase of Coal Generation: ' + str(round(average_ratio_total, 2)) + '%')

for i in range(10):
  buffer = round(total_gen[len(total_gen) - 1] * (1 + average_ratio_total / 100))
  total_gen.append(round(total_gen[len(total_gen) - 1] * (1 + average_ratio_total / 100)))
  for i in range(len(total_gen) - 1):
    total_per.append(round((((total_gen[(i + 1)] - total_gen[i]) / total_gen[i]) * 100), 5))
  print('Power generated is ' + str(buffer) + ' due to ' + str(total_per[-1]) + '% increase.')
  average_ratio_total = sum(total_per) / len(total_per)

print(total_gen)

# 15. Effects of Adoption of Renewable Fuel Sources on the Dependency on Non-Renewable Fuel Sources

renewables = ['Biomass', 'Geothermal', 'Hydro', 'Solar', 'Wind']
rc = 0

plt.figure(figsize=(20, 16))
for i in range(length):
    if list_of_fuels[i] in renewables:
      plt.plot(pgfsDF['Years'], pgfsDF[list_of_fuels[i]], label=list_of_fuels[i], linewidth = 4, linestyle=':')
    else:
      plt.plot(pgfsDF['Years'], pgfsDF[list_of_fuels[i]], label=list_of_fuels[i], linewidth = 2, linestyle=':')

plt.legend(fontsize = 25, title = 'Fuel Sources')
plt.title('Share of Renewable Energy Sources')
plt.xlabel('Years')
plt.ylabel('Grand Total')
plt.xticks(list_of_years, rotation=45)
plt.grid()
plt.tight_layout()
plt.show()

# 16. Possible Implications of current trends on Future Energy Policies